#234 Reverted back to importing from rxjs/Rx
Last commit made the build server error by 
`error TS2339: Property 'xxx' does not exist on type 'Observable'`

Sticking with this import method